### ISSUE TITLE
用css画一个三角形

### ISSUE THREAD

**Issue by MMLucy** [chris-paul/no-step-no-mile#10]

**Comment by MMLucy** [comment]
右箭头
```css
.arrow {
    border: 5px solid;
    border-color: #ff6e0d #ff6e0d transparent transparent;
    transform: rotate(45deg);
    display: inline-block;
}
```
```html
<i class="arrow"></i>
```
效果图如下：
![image](https://user-images.githubusercontent.com/23635143/117602664-d22e1680-b183-11eb-87c8-53053ab395c1.png)

左箭头
```css
.arrow {
    border: 5px solid;
    border-color: #ff6e0d transparent transparent #ff6e0d;
    transform: rotate(-45deg);
    display: inline-block;
}
```
![image](https://user-images.githubusercontent.com/23635143/117602884-4d8fc800-b184-11eb-8f92-e6e0fdb7e10b.png)
