### ISSUE TITLE
垂直居中的方式有哪些

### ISSUE THREAD

**Issue by chris-paul** [chris-paul/no-step-no-mile#15]

**Comment by MMLucy** [comment]
```css
.test {
    line-height: 30px;
    height: 30px;
}
```
```css
.parent {
     position: relative;
}
.child {
     position: absolute;
     top: 50%;
     left: 50%;
     transform: translate(-50%,-50%);
}
```
```css
.test {
     display: flex;
     align-items: center;
}
```
```css
.test {
    display: table-cell;
    vertical-align: middle;
}
```
