### ISSUE TITLE
实现文字超过一定宽度后，以省略号展示，可以通过 JS/CSS 实现

### ISSUE THREAD

**Issue by chris-paul** [chris-paul/no-step-no-mile#8]

**Comment by MMLucy** [comment]
css写法：

单行文本超出，后面使用省略号
```css
p {
    white-space: nowrap;  // 强制不换行
    text-overflow: ellipsis;  
    overflow: hidden;
    width: 100px;
}
```
![444](https://user-images.githubusercontent.com/23635143/117613897-23490500-b19a-11eb-9f33-3a4d71d68a69.png)

多行文本超出：
```css
p {
    text-overflow: ellipsis;
    overflow: hidden;
    display: -webkit-box;
    -webkit-line-clamp: 3;
    -webkit-box-orient: vertical;
}
```
![image](https://user-images.githubusercontent.com/23635143/117613931-2e039a00-b19a-11eb-88cb-a283ab99d053.png)

**Comment by MMLucy** [comment]
css写法：

单行文本超出，后面使用省略号
```css
p {
    white-space: nowrap;  // 强制不换行
    text-overflow: ellipsis;  
    overflow: hidden;
    width: 100px;
}
```
![444](https://user-images.githubusercontent.com/23635143/117613897-23490500-b19a-11eb-9f33-3a4d71d68a69.png)

多行文本超出：
```css
p {
    text-overflow: ellipsis;
    overflow: hidden;
    display: -webkit-box;
    -webkit-line-clamp: 3;
    -webkit-box-orient: vertical;
}
```
![image](https://user-images.githubusercontent.com/23635143/117613931-2e039a00-b19a-11eb-88cb-a283ab99d053.png)
